const REGISTRATION_ENDPOINT = 'PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE';
const form = document.getElementById('registrationForm');
const fileInput = document.getElementById('paymentProof');
const dropzone = document.getElementById('dropzone');
const fileName = document.getElementById('fileName');
const message = document.getElementById('formMessage');
function showFile(){const f=fileInput.files[0];fileName.textContent=f?`Selected: ${f.name}`:''}
fileInput.addEventListener('change',showFile);
['dragenter','dragover'].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.classList.add('active')}));
['dragleave','drop'].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.classList.remove('active')}));
dropzone.addEventListener('drop',e=>{const files=e.dataTransfer.files;if(files.length){fileInput.files=files;showFile()}});
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);})}
form.addEventListener('submit',async e=>{e.preventDefault();message.className='form-message';message.textContent='';if(!form.checkValidity()){form.reportValidity();message.classList.add('error');message.textContent='Please complete all required fields and upload your payment screenshot.';return}const file=fileInput.files[0];if(!file){message.classList.add('error');message.textContent='Please upload your payment screenshot.';return}if(file.size>4*1024*1024){message.classList.add('error');message.textContent='Please upload a payment screenshot smaller than 4 MB.';return}if(REGISTRATION_ENDPOINT.includes('PASTE_YOUR')){message.classList.add('error');message.textContent='The registration service still needs its Google Apps Script web-app URL. See SETUP.md.';return}const submit=form.querySelector('.submit');submit.disabled=true;submit.textContent='Submitting…';try{const payload={fullName:form.fullName.value.trim(),email:form.email.value.trim(),phone:form.phone.value.trim(),location:form.location.value.trim(),committee:form.committee.value,paymentFileName:file.name,paymentScreenshot:await fileToDataUrl(file)};await fetch(REGISTRATION_ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});message.className='form-message success';message.textContent='Registration submitted successfully. Your FQMUN registration is now under review. Please keep your payment receipt.';form.reset();fileName.textContent=''}catch(err){message.className='form-message error';message.textContent='Submission failed. Please try again or contact FQMUN.'}finally{submit.disabled=false;submit.innerHTML='Submit registration <span>↗</span>'}});